# Generated by Django 2.2 on 2020-08-18 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_spending_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weekly_food', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weekly_personal', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weekly_transportation', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weekly_housing', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weekly_other', models.DecimalField(decimal_places=2, max_digits=11)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
